### PR TITLE
Update ProceduralDungeonEdTypes.h

### PR DESCRIPTION
**Pull request by Microquantus**
add Fmargin3D construction script

### CODE REVIEW

**Comment by Microquantus** [comment]
fix logError
屏幕截图 2024-04-15 084938

**Comment by BenPyton** [comment]
Hi @Microquantus 
I don't have any compilation error when I packaged the plugin.
Could you provide just some more info on your error, please?
- What UE version throws this error?
- What platform are you compiling for and from? (Windows, Mac)

Also, I'm wondering if you could just initialize them like that:
```cpp
FVector2D XAxis {FVector2D::ZeroVector};
```
It would be consistent with the code in the plugin.

**Comment by Microquantus** [comment]
Every time UE is launched, an error is reported in the output log.

**Comment by BenPyton** [comment]
Hi @Microquantus 
Did you closed the PR by mistake?
If not, could you tell why, please?

Also, did you tried with the [default member initialization](https://www.learncpp.com/cpp-tutorial/default-member-initialization/) as I suggested, instead of the constructor?

If it works with the default member initialization, I would be glad to merge your PR :)

**Comment by Microquantus** [comment]
> Hi @Microquantus Did you closed the PR by mistake? If not, could you tell why, please?
> 
> Also, did you tried with the [default member initialization](https://www.learncpp.com/cpp-tutorial/default-member-initialization/) as I suggested, instead of the constructor?
> 
> If it works with the default member initialization, I would be glad to merge your PR :)

sry, the PR is not working,it still log error.
I successfully resolved the error using your suggestion.
`// Holds margin values in 3D (e.g. used for box volumes)
USTRUCT()
struct FMargin3D
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "Margin", meta = (DisplayName = "X"))
	FVector2D XAxis{0.0f, 0.0f};

	UPROPERTY(EditAnywhere, Category = "Margin", meta = (DisplayName = "Y"))
	FVector2D YAxis{0.0f, 0.0f};

	UPROPERTY(EditAnywhere, Category = "Margin", meta = (DisplayName = "Z"))
	FVector2D ZAxis{0.0f, 0.0f};

	// Create a new bounds from an existing bounds with the margin applied on it.
	FBoxCenterAndExtent Apply(const FBoxCenterAndExtent& Bounds) const;
};`

**Pull request closed without merging**
